package ru.apteka.making_order_api.api

/**
 * Возвращает ключ аргумента.
 */
const val MAKING_ORDER_ARGUMENT_PRODUCT = "productsForOrder"   //Используется в аргументах между фрагментами.
const val MAKING_ORDER_ARGUMENT_COMPLETION = "completionData"   //Используется в аргументах между фрагментами.
const val MAKING_ORDER_ARGUMENT_DELIVERY = "MAKING_ORDER_ARGUMENT_DELIVERY"
const val MAKING_ORDER_ARGUMENT_DELIVERY_DATA = "MAKING_ORDER_ARGUMENT_DELIVERY_DATA"
const val MAKING_ORDER_ARGUMENT_RECIPIENTS = "MAKING_ORDER_ARGUMENT_RECIPIENTS"
const val MAKING_ORDER_ARGUMENT_RECIPIENTS_DATA = "MAKING_ORDER_ARGUMENT_RECIPIENTS_DATA"
const val MAKING_ORDER_ARGUMENT_COMPLETION_BACK = "MAKING_ORDER_ARGUMENT_COMPLETION_BACK"
